/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample;

import com.stripe.Stripe;
import com.stripe.exception.StripeException;
import com.stripe.model.terminal.Reader;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

public class App {
    public static void main(String[] args) throws IOException, StripeException {
        Stripe.apiKey = Files.readString(Path.of(System.getProperty("user.dir") + "/../../api_key"));
        Reader.retrieve("tmr_EihpMAqu6AYhxl").getTestHelpers().simulatePayment();
    }
}
